CREATE TABLE pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mesa INT NOT NULL,
  producto VARCHAR(100) NOT NULL,
  cantidad INT NOT NULL,
  area VARCHAR(50) NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
